### ISSUE TITLE
Create a contact and add it to a list

### ISSUE THREAD

**Issue by ElliotCK1** [sendinblue/APIv3-csharp-library#46] opened 2021-10-26 07:55 UTC
Hello,

I am trying to create a contact from my website with C#. To do it, I followed the documentation on this page : https://developers.sendinblue.com/reference/createcontact
Unfortunately, I have an error as you can see on the next screenshot : 
![github_screen](https://user-images.githubusercontent.com/93184823/138832887-0525f144-a710-41fe-877a-1a8124a2a833.png)

The error is that the key already exists in the dictionnary. I don't understand this error because for me, this line is to connect my SendinBlue account with my website so of course the key exists...

If someone already had this problem or if anyone knows what should I do to fix the problem ?

Thanks

**Comment by nghaninn** [comment] 2021-11-05 09:59
Duplicate of #43 look at @jap64's solution.

Alternatively you can always declare new apikey
` var configuration = new sib_api_v3_sdk.Client.Configuration();
 configuration.ApiKey.Add("api-key", <<SendinblueApiKey>>);
 var apiInstance = new TransactionalEmailsApi(configuration);`

**Comment by amitsendinblue** [comment] 2021-11-12 05:16
Closing this issue as it's duplicate of [#43](https://github.com/sendinblue/APIv3-csharp-library/issues/43)

**Closed as completed by amitsendinblue** 2021-11-12 05:16 UTC
